Repository argrelay/argrelay, pull requests merged in 2023-02, with the labels that each got.

#9 Fix: skip non-serializable `_id` on `Schema.dump`
  argrelay-rc.bash
  build-git-env.bash
  dev-init.bash
  dev-shell.bash
  docs/dev_notes/deployment_procedure.md
  docs/dev_notes/dev_env_and_target_env_diff.md
  docs/dev_notes/screen_cast_notes.md
  docs/dev_notes/top_todos.md
  docs/feature_stories/FS_55_57_45_04.demo_logic.md
  docs/test_data/TD_63_37_05_36.demo_services_data.md
  publish-package.bash
  readme.md
  setup.py
  src/argrelay/custom_integ/CodeMaturityProcessor.py
  src/argrelay/custom_integ/DemoInterp.py
  src/argrelay/custom_integ/DemoInterpConfigSchema.py
  src/argrelay/custom_integ/DemoInterpFactory.py
  src/argrelay/custom_integ/GitRepoArgType.py
  src/argrelay/custom_integ/GitRepoEnvelopeClass.py
  src/argrelay/custom_integ/GitRepoInvocator.py
  src/argrelay/custom_integ/GitRepoLoader.py
  src/argrelay/custom_integ/GitRepoLoaderConfigSchema.py
  src/argrelay/custom_integ/ServiceArgType.py
  src/argrelay/custom_integ/ServiceEnvelopeClass.py
  src/argrelay/custom_integ/ServiceLoader.py
  src/argrelay/custom_integ/ServiceLoaderConfigSchema.py
  src/argrelay/custom_integ/__init__.py
  src/argrelay/custom_integ/argrelay-rc.bash
  src/argrelay/custom_integ/argrelay.client.json
  src/argrelay/custom_integ/argrelay.server.yaml
  src/argrelay/custom_integ/build-git-env.bash
  src/argrelay/custom_integ/build-pip-env.bash
  src/argrelay/custom_integ/deploy-artifacts.bash
  src/argrelay/custom_integ/dev-init.bash
  src/argrelay/custom_integ/dev-shell.bash
  src/argrelay/mongo_data/MongoClientWrapper.py
  src/argrelay/schema_config_core_server/FirstArgInterpFactorySchema.py
  src/argrelay/schema_config_interp/DataEnvelopeSchema.py
  src/argrelay/schema_response/FilteredDict.py
  src/argrelay/schema_response/InvocationInputSchema.py
  src/argrelay/test_helper/EnvMockBuilder.py
  tests/env_tests/test_MongoClient_envelope_search.py
  tests/env_tests/test_MongoClient_tutorial.py
  tests/env_tests/test_relay_client_relay_line_args.py
  tests/offline_tests/interp_plugin/test_FirstArgInterp.py
  tests/offline_tests/interp_plugin/test_FuncArgsInterpFactory.py
  tests/offline_tests/relay_demo/test_relay_demo.py
  tests/offline_tests/relay_server/test_data_dump_on_server.py
  tests/offline_tests/schema_common/test_Schema.py
  tests/offline_tests/schema_config_core_server/test_StaticDataSchema.py
  tests/offline_tests/test_helper/test_TD_63_37_05_36_default.py
  tests/online_tests/relay_demo/test_GitRepoLoader.py
  tests/online_tests/relay_demo/test_run_argrelay_client.py
  tests/release_tests/test_pre_publish.py
Labels: bug

#11 Use path to venv configured externally
  publish-package.bash
  src/argrelay/custom_integ/build-git-env.bash
  src/argrelay/custom_integ/dev-init.bash
Labels: enhancement, good first issue

#13 Add LRU query cache with TTL
  docs/dev_notes/query_perf_cache_vs_no_cache.md
  src/argrelay/custom_integ/ServiceLoader.py
  src/argrelay/custom_integ/argrelay.server.yaml
  src/argrelay/handler_request/AbstractServerRequestHandler.py
  src/argrelay/relay_server/LocalServer.py
  src/argrelay/relay_server/QueryCacheConfig.py
  src/argrelay/relay_server/QueryEngine.py
  src/argrelay/relay_server/QueryResult.py
  src/argrelay/runtime_context/EnvelopeContainer.py
  src/argrelay/runtime_context/InterpContext.py
  src/argrelay/runtime_data/ServerConfig.py
  src/argrelay/schema_config_core_server/QueryCacheConfigSchema.py
  src/argrelay/schema_config_core_server/ServerConfigSchema.py
  src/argrelay/test_helper/EnvMockBuilder.py
  tests/offline_tests/relay_server/test_QueryEngine.py
  tests/release_tests/test_pre_publish.py
Labels: enhancement

#14 Populate `ImplicitValue` from multiple envelopes
  docs/dev_notes/top_todos.md
  docs/feature_stories/FS_06_99_43_60.list_arg_value.md
  src/argrelay/client_command_remote/ProposeArgValuesRemoteClientCommand.py
  src/argrelay/custom_integ/GitRepoInvocator.py
  src/argrelay/custom_integ/ServiceLoader.py
  src/argrelay/handler_request/RelayLineArgsServerRequestHandler.py
  src/argrelay/plugin_interp/FuncArgsInterp.py
  src/argrelay/plugin_invocator/AbstractInvocator.py
  src/argrelay/relay_server/QueryEngine.py
  src/argrelay/runtime_context/EnvelopeContainer.py
  src/argrelay/runtime_context/InterpContext.py
  tests/offline_tests/relay_demo/test_relay_demo.py
  tests/offline_tests/relay_server/test_QueryEngine.py
Labels: bug, enhancement
